title: Cepalium

author:
  name: Tuan Nguyen

url: "https://cepalium.github.io"

minima:
  social_links:
    email: tuan15096@gmail.com
    linkedin: tuanang
    github: cepalium
    rss: true

# Google services
google_analytics: UA-168736039-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap