title: Cepalium

author:
  name: Tuan Nguyen

domain: cepalium.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cepalium.github.io  # the base hostname and protocol for your site, e.g. http://example.com

minima:
  social_links:
    email: tuan15096@gmail.com
    linkedin: tuanang
    github: cepalium
    rss: true

# Google services
google_analytics: UA-168736039-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
